In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [3]:
df=pd.read_csv("E:\ML-codebasics\lineaRegression-multipleVariable\homeprices.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [4]:
import math
median_bedrooms = math.floor(df.bedrooms.median())
median_bedrooms

3

In [5]:
df.bedrooms.fillna(median_bedrooms)

0    3.0
1    4.0
2    3.0
3    3.0
4    5.0
Name: bedrooms, dtype: float64

In [6]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

In [8]:
#creating a linear regression object
reg = linear_model.LinearRegression()
#train model using fit method
#independent variables-(area, bedroom, age) & target variable-(price)
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

# price= m1*area + m2*bedrooms + m3*age + b
m1,m2,m3 are coefficients
b is intercept
area,bedrooms,age-Independent Variables(features)
price-Dependent Variable

In [9]:
#m1,m2,m3
reg.coef_

array([   137.25, -26025.  ,  -6825.  ])

In [10]:
#b(intercept)
reg.intercept_

383725.0

In [13]:
#example from table -Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old
reg.predict([[3000, 3, 40]])

C:\Users\aarushi saxena\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [12]:
# price= m1*area + m2*bedrooms + m3*age + b(checking above price)
137.25*3000 + -26025*3 + -6825*40 + 383725

444400.0

In [14]:
reg.predict([[2500, 4, 5]])

C:\Users\aarushi saxena\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])